import React, { useState, useEffect } from 'react';
import { db } from '../lib/firebase';
import { collection, addDoc, onSnapshot, doc, deleteDoc } from 'firebase/firestore';
import { useAuth } from '../contexts/AuthContext';
import { ShieldAlert, Plus, Trash2, KeyRound } from 'lucide-react';
import { format } from 'date-fns';

interface CodigoAcceso {
  id: string;
  rol: 'admin' | 'cajero';
  usado: boolean;
  usadoPor?: string;
  creadoPor: string;
  creadoEn: number;
}

export default function PanelCreador() {
  const { role, user } = useAuth();
  const [codigos, setCodigos] = useState<CodigoAcceso[]>([]);
  const [generando, setGenerando] = useState(false);

  useEffect(() => {
    if (role !== 'superadmin') return;

    const unsub = onSnapshot(collection(db, 'codigos'), (snap) => {
      const data = snap.docs.map(d => ({ id: d.id, ...d.data() } as CodigoAcceso));
      setCodigos(data.sort((a,b) => b.creadoEn - a.creadoEn));
    });

    return () => unsub();
  }, [role]);

  const generarCodigo = async (rol: 'admin' | 'cajero') => {
    if (!user) return;
    setGenerando(true);
    try {
      // 6 random alphanumeric chars
      const codigoRaw = Math.random().toString(36).substring(2, 8).toUpperCase();
      
      await addDoc(collection(db, 'codigos'), {
        rol,
        usado: false,
        creadoPor: user.uid,
        creadoEn: Date.now()
      });
      // The id in DB will be the actual code, wait! 
      // Right now the code is auto-generated by Firestore (`addDoc`). We should set doc id explicitly to be the `codigoRaw`.
    } catch (err) {
      console.error(err);
      alert("Error al generar código.");
    } finally {
      setGenerando(false);
    }
  };

  const generarCodigoConIdPropio = async (rol: 'admin' | 'cajero') => {
    if (!user) return;
    setGenerando(true);
    try {
      const codigoParams = Math.random().toString(36).substring(2, 8).toUpperCase();
      import("firebase/firestore").then(({ setDoc, doc }) => {
         setDoc(doc(db, 'codigos', codigoParams), {
            rol,
            usado: false,
            creadoPor: user.uid,
            creadoEn: Date.now()
         }).then(() => alert("CÓDIGO GENERADO. Revisa la lista."))
         .catch(err => alert("Error al generar código."));
      });
    } catch (err) {
      console.error(err);
      alert("Error al generar código.");
    } finally {
      setGenerando(false);
    }
  };

  const eliminarCodigo = async (id: string) => {
    if (!confirm('¿Seguro que desea eliminar este código?')) return;
    try {
      await deleteDoc(doc(db, 'codigos', id));
    } catch (err) {
      console.error(err);
      alert("Error al eliminar código.");
    }
  };

  if (role !== 'superadmin') {
    return <div className="p-8 text-center text-gray-500 font-bold uppercase tracking-widest">ACCESO DENEGADO</div>;
  }

  return (
    <div className="flex flex-col gap-6 p-4 md:p-6 overflow-y-auto w-full max-h-screen">
      <div className="flex items-center gap-3 text-red-600 border-b-2 border-black pb-4">
        <ShieldAlert size={32} />
        <h1 className="text-2xl font-extrabold tracking-tighter text-gray-900 uppercase">Panel Super Admin</h1>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Generar Código Dueña */}
        <div className="bg-white p-6 border-2 border-black flex flex-col gap-4 group hover:bg-orange-50 transition-colors">
          <div className="flex justify-between items-center">
            <h2 className="font-extrabold text-lg uppercase tracking-wider">Código para Dueña</h2>
            <KeyRound className="text-orange-500" />
          </div>
          <p className="text-xs text-gray-500 font-medium">
            Genera un código de un solo uso para que la dueña obtenga permisos totales.
          </p>
          <button
            onClick={() => generarCodigoConIdPropio('admin')}
            disabled={generando}
            className="mt-auto bg-black text-white hover:bg-zinc-800 font-bold py-3 uppercase tracking-widest flex justify-center items-center gap-2 transition-all disabled:opacity-50"
          >
            <Plus size={18} /> Crear Código Admin
          </button>
        </div>

        {/* Generar Código Cajero */}
        <div className="bg-white p-6 border-2 border-black flex flex-col gap-4 group hover:bg-gray-50 transition-colors">
          <div className="flex justify-between items-center">
            <h2 className="font-extrabold text-lg uppercase tracking-wider">Código para Cajera</h2>
            <KeyRound className="text-blue-500" />
          </div>
          <p className="text-xs text-gray-500 font-medium">
            Genera un código de un solo uso para que la empleada obtenga permisos de venta.
          </p>
          <button
            onClick={() => generarCodigoConIdPropio('cajero')}
            disabled={generando}
            className="mt-auto border-2 border-black bg-white text-black hover:bg-black hover:text-white font-bold py-3 uppercase tracking-widest flex justify-center items-center gap-2 transition-all disabled:opacity-50"
          >
            <Plus size={18} /> Crear Código Cajero
          </button>
        </div>
      </div>

      <div className="bg-white border-2 border-black flex-1 flex flex-col mt-4">
        <div className="p-4 border-b border-black flex justify-between items-center bg-gray-50">
          <h2 className="font-black uppercase tracking-widest text-sm">Códigos Emitidos</h2>
          <span className="font-mono text-xs bg-black text-white px-2 py-1">{codigos.length}</span>
        </div>
        <div className="overflow-x-auto min-h-[300px] p-0">
          <table className="w-full text-left text-sm whitespace-nowrap">
            <thead className="border-b border-gray-200 text-gray-500 uppercase text-[10px] tracking-widest">
              <tr>
                <th className="p-4 font-bold">Código (Token)</th>
                <th className="p-4 font-bold">Rol</th>
                <th className="p-4 font-bold">Estado</th>
                <th className="p-4 font-bold">Fecha</th>
                <th className="p-4 font-bold text-right">Acción</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {codigos.map(cod => (
                <tr key={cod.id} className="hover:bg-gray-50 transition-colors">
                  <td className="p-4 font-mono font-bold text-lg text-gray-900 cursor-all-scroll select-all tracking-wider">{cod.id}</td>
                  <td className="p-4">
                    <span className={`px-2 py-0.5 font-black uppercase text-[10px] tracking-widest ${cod.rol === 'admin' ? 'bg-orange-100 text-orange-700' : 'bg-gray-200 text-gray-700'}`}>
                      {cod.rol}
                    </span>
                  </td>
                  <td className="p-4">
                    <span className={`px-2 py-0.5 font-bold uppercase text-[10px] tracking-widest ${cod.usado ? 'bg-red-100 text-red-700 block text-center' : 'bg-green-100 text-green-700 block text-center'}`}>
                      {cod.usado ? 'USADO' : 'DISPONIBLE'}
                    </span>
                  </td>
                  <td className="p-4 text-xs text-gray-500 font-mono">{format(cod.creadoEn, 'dd/MM/yy HH:mm')}</td>
                  <td className="p-4 text-right">
                    <button onClick={() => eliminarCodigo(cod.id)} className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded transition-all">
                      <Trash2 size={18} />
                    </button>
                  </td>
                </tr>
              ))}
              {codigos.length === 0 && (
                <tr><td colSpan={5} className="p-8 text-center text-gray-400 uppercase tracking-widest font-bold text-xs">Aún no has generado códigos.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
